### PR TITLE
Upgrade to use purity inference

### PR DESCRIPTION
**Pull request by smores56**
Purity inference [has been merged](https://github.com/roc-lang/roc/pull/7170), so once the `return` fix is ready in [this PR](https://github.com/roc-lang/roc/pull/7204), we can validate this PR and then merge.

### CODE REVIEW

**Comment by lukewilliamboswell** [comment]
@smores56 

I think we should land this. It would keep our basic-cli `build.roc` script simple, just need a new Weaver release. Otherwise we have to do the breaking change, jump-start thing.

**Comment by lukewilliamboswell** [comment]
Never mind... I found other issues, and so simplified the build script to not use Weaver or any arg parsing as a dependency.

**Comment by smores56** [comment]
Glad to hear it's not breaking anymore. I'd like to, if possible, merge [allowing pure statements that contain early returns](https://github.com/roc-lang/roc/pull/7238) since it cleans up code with multiple `try`s in `Validate.roc`. If that can get merged in the next 12 hours or so, then I'll fix that up and then merge this. It's not blocking, though, so I'll merge this tomorrow morning otherwise.

**Comment by smores56** [comment]
This can be merged once https://github.com/roc-lang/roc/pull/7286 is merged and we double-check against it. We'll keep having type errors until then.

**Pull request merged**
